# Site settings
title: Apache PDFBox | A Java PDF Library
description: > # this means to ignore newlines until "baseurl:"
  The Apache PDFBox™ library is an open source Java tool for working with PDF documents.
  This project allows creation of new PDF documents, manipulation of existing documents
  and the ability to extract content from documents. Apache PDFBox also includes several
  command line utilities. Apache PDFBox is published under the Apache License v2.0.
baseurl: ""
url: "http://pdfbox.apache.org/"


# Build settings
source: ./content
destination: ./staging
layouts_dir:  _layouts

markdown_ext: "markdown,mkdown,mkdn,mkd,md,mdtext"

encoding: UTF-8
markdown: redcarpet

redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

